name: Build and Publish

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - uses: olegtarasov/get-tag@v2.1.1
        if: startsWith(github.ref, 'refs/tags/')
        id: tagName
      - name: Set versions
        if: startsWith(github.ref, 'refs/tags/')
        env:
          ARTIFACT_VERSION: ${{ steps.tagName.outputs.tag }}
        run: mvn versions:set -DnewVersion=${{ steps.tagName.outputs.tag }}
      - name: Build with Maven
        run: mvn -B package
      - name: Cache build artifacts
        id: cache-maven-artifacts
        uses: actions/cache@v3
        with:
          path: target
          key: artifacts-${{github.run_number}}-${{github.run_attempt}}
    outputs:
      tagName: ${{ steps.tagName.outputs.tag }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
          - linux/amd64
          - linux/arm/v6
          - linux/arm/v7
          - linux/arm64
    steps:
      - uses: actions/checkout@v3
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/flixtraktor:$BUILDNUMBER
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Cache build artifacts
        id: cache-maven-artifacts
        uses: actions/cache@v3
        with:
          path: target
          key: artifacts-${{github.run_number}}-${{github.run_attempt}}
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          build-args: |
            JAR_FILE=target/flixtraktor-${{ needs.build.outputs.tagName }}.jar
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/flixtraktor:${{ needs.build.outputs.tagName }},${{ secrets.DOCKER_USERNAME }}/flixtraktor:latest