name: Build and Publish

on:
  push:
    branches: [ main ]
    tags:
      - '*'
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - uses: olegtarasov/get-tag@v2.1.1
      if: startsWith(github.ref, 'refs/tags/')
      id: tagName
    - name: Set versions
      if: startsWith(github.ref, 'refs/tags/')
      env:
        ARTIFACT_VERSION: ${{ steps.tagName.outputs.tag }}
      run: mvn versions:set -DnewVersion=${{ steps.tagName.outputs.tag }}
    - name: Build with Maven
      run: mvn -B package
    - name: Cache build artifacts
      id: cache-maven-artifacts
      uses: actions/cache@v3
      with:
        path: target
        key: artifacts-${{github.run_number}}-${{github.run_attempt}}
    outputs:
      tagName: ${{ steps.tagName.outputs.tag }}

  publish:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Cache build artifacts
      id: cache-maven-artifacts
      uses: actions/cache@v3
      with:
        path: target
        key: artifacts-${{github.run_number}}-${{github.run_attempt}}
    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: Deploy Docker image
      env:
        BUILDNUMBER: ${{needs.build.outputs.tagName}}
      run: |
        docker build . --build-arg JAR_FILE=target/flixtraktor-$BUILDNUMBER.jar \
          --tag ${{ secrets.DOCKER_USERNAME }}/flixtraktor:$BUILDNUMBER
        docker push ${{ secrets.DOCKER_USERNAME }}/flixtraktor:$BUILDNUMBER